"""empty message

Revision ID: 2d08aaa51db5
Revises: 
Create Date: 2022-10-22 16:21:48.170502

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2d08aaa51db5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_question', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('user_answer', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('user_answer', 'quiz_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_answer', sa.Column('quiz_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('user_answer', 'id')
    op.drop_column('quiz_question', 'id')
    # ### end Alembic commands ###
