"""empty message

Revision ID: 45775bfe0caa
Revises: b65b0c5e70d0
Create Date: 2022-11-09 15:33:11.800774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45775bfe0caa'
down_revision = 'b65b0c5e70d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz',
    sa.Column('quiz_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('quiz_id')
    )
    op.create_table('quiz_question',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_question')
    op.drop_table('quiz')
    # ### end Alembic commands ###
