"""empty message

Revision ID: 6290dfad9b6f
Revises: 5da0e5cd715f
Create Date: 2022-11-09 18:47:12.105233

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6290dfad9b6f'
down_revision = '5da0e5cd715f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_answer', sa.Column('user_answer', sa.String(length=256), nullable=True))
    op.drop_column('user_answer', 'answer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_answer', sa.Column('answer', mysql.VARCHAR(length=256), nullable=True))
    op.drop_column('user_answer', 'user_answer')
    # ### end Alembic commands ###
