"""empty message

Revision ID: b81f404b9134
Revises: c0063a46c5e1
Create Date: 2022-11-02 17:40:53.450296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b81f404b9134'
down_revision = 'c0063a46c5e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('img_url', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'img_url')
    # ### end Alembic commands ###
