"""Initial migration.

Revision ID: be15d781cf76
Revises: c5a6f8cfd747
Create Date: 2022-12-06 22:07:04.059269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be15d781cf76'
down_revision = 'c5a6f8cfd747'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('question_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('q_type', sa.Integer(), nullable=True),
    sa.Column('c_type', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('content', sa.String(length=1024), nullable=True),
    sa.Column('answer', sa.String(length=256), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('quiz',
    sa.Column('quiz_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('quiz_id')
    )
    op.create_table('quiz_question',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_answer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('quiz_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('user_answer', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_answer')
    op.drop_table('quiz_question')
    op.drop_table('quiz')
    op.drop_table('question')
    # ### end Alembic commands ###
