"""Initial migration.

Revision ID: c5a6f8cfd747
Revises: 12b1a8c8d7e7
Create Date: 2022-12-06 21:36:54.304325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5a6f8cfd747'
down_revision = '12b1a8c8d7e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_answer', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_answer', 'created_at')
    # ### end Alembic commands ###
