DOG_INFO_API_URL = "http://doggo-env-0.eba-zsw3tn3r.us-east-2.elasticbeanstalk.com"
DOG_ALL_URL = DOG_INFO_API_URL + "/dogs"
DOG_ONE_URL = DOG_ALL_URL + "/{}"
DOG_CATEGORIES_URL = DOG_ONE_URL + "/categories"
DOG_ORIGINS_URL = DOG_ONE_URL + "/origins"
DOG_SIZE_URL = DOG_ONE_URL + "/size"
DOG_IMAGE_URL = DOG_ONE_URL + "/image_url"
DOG_PRONUNCIATION_URL = DOG_ONE_URL + "/pronunciation"
